{"name": "Autorization with invalid user", "status": "passed", "steps": [{"name": "Open login page", "status": "passed", "start": 1746872813812, "stop": 1746872817696}, {"name": "Fill invalid user data", "status": "passed", "start": 1746872817696, "stop": 1746872817769}, {"name": "Error Displayed - Invalid credentials. Please try again.", "status": "passed", "start": 1746872817769, "stop": 1746872817774}], "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1746872813812, "stop": 1746872817774, "uuid": "9a2b8b55-2e55-404a-8e0c-931dbd223ae2", "historyId": "3230c37a4ddf37e226b736e144aaba65", "testCaseId": "89a909a1ca222b871b75e39c89c26fa1", "fullName": "tests.test_login#test_login_failure", "labels": [{"name": "feature", "value": "Autorization"}, {"name": "severity", "value": "critical"}, {"name": "story", "value": "Autorization with invalid user"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-S0PIHSG"}, {"name": "thread", "value": "28192-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}